### ISSUE TITLE
Query NARR data from THREDDS server

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#1475]
Is NARR available through a THREDDS server? If so, it would make the met workflow for NARR simpler and less data intensive if we can do server-side subsetting before download.

We discussed this in the PEcAn meeting and @ankurdesai suggested I make an issue and he would check to see if this is available.

### TODO

* [ ] search if there is an up to date THREDDS server with NARR data
* [ ] if so, how hard would it be to update code?
* [ ] if applicable create new issues to handle updating code

**Comment by dlebauer** [comment]
duplicated by #1476
